ailu:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 120.46.95.186
    port: 3306
    database: tiny_universe
    username: root
    password: 123456

    minio:
      endpoint: http://120.46.95.186:9000
      accessKey: ailu
      secretKey: dfDF51d5
      bucket: public

  redis:
    database: 2
    host: 120.46.95.186
    port: 6379
    user: default
    password: 123456

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://120.46.95.186:12001/xxl-job-admin
    executor:
      address: ''
      appname: tiny-universe
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999


