server:
  port: 8082


spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  datasource:
    druid:
      driver-class-name: ${ailu.datasource.driver-class-name}
      url: jdbc:mysql://${ailu.datasource.host}:${ailu.datasource.port}/${ailu.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${ailu.datasource.username}
      password: ${ailu.datasource.password}
  redis:
    database: ${ailu.redis.database}
    host: ${ailu.redis.host}
    port: ${ailu.redis.port}
    password: ${ailu.redis.password}
  mail:
    host: smtp.qq.com  #SMTP服务器地址
    username: 2568315961@qq.com #登陆账号
    password: jqefjzyibkbkecfb #登陆密码（或授权码）
    port: 587
    properties:
      from: 2568315961@qq.com #邮件发信人（即真实邮箱）

  freemarker:
    # 启用 freemarker 模板
    enabled: true
    # 是否缓存
    cache: false
    # Content Type
    content-type: text/html
    # 编码
    charset: utf-8
    # 模板后缀
    suffix: .ftl
    # 引用 request 的属性名称
    request-context-attribute: request
    # 是否暴露 request 域中的属性
    expose-request-attributes: false
    # 是否暴露session域中的属性
    expose-session-attributes: false
    # request 域中的属性是否可以覆盖 controller 的 model 的同名项。默认 false，如果发生同名属性覆盖的情况会抛出异常
    allow-request-override: true
    # session 域中的属性是否可以覆盖 controller 的 model 的同名项。默认 false，如果发生同名属性覆盖的情况会抛出异常
    allow-session-override: true
    # 暴露官方提供的宏
    expose-spring-macro-helpers: true
    # 启动时检查模板位置是否有效
    check-template-location: true
    # 优先加载文件系统的模板
    prefer-file-system-access: true
    # 模板所在位置（目录）
    template-loader-path:
      - classpath:/templates/
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss      # date 输出格式化
      template_update_delay: 30m                # 模板引擎刷新时间
      default_encoding: utf-8

minio:
  endpoint: ${ailu.datasource.minio.endpoint}
  accessKey: ${ailu.datasource.minio.accessKey}
  secretKey: ${ailu.datasource.minio.secretKey}
  bucket: ${ailu.datasource.minio.bucket}

ailu:
  jwt:
    secret: ailu
    expiration: 604800000


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ailu.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      ailu:
        mapper: debug
        service: info
        controller: info

xxl:
  job:
    accessToken: ${xxl.job.accessToken}
    admin:
      addresses: ${xxl.job.admin.addresses}
    executor:
      address: ${xxl.job.executor.address}
      appname: ${xxl.job.executor.appname}
      ip: ${xxl.job.executor.ip}
      logpath: ${xxl.job.executor.logpath}
      logretentiondays: ${xxl.job.executor.logretentiondays}
      port: ${xxl.job.executor.port}

qianfan:
  appID: 92565648
  APIKey: 449k1dEkappNvotvX1Hmb6j3
  SecretKey: mZcN7L8m0Qd8A7RKDtN9CNXncAAzrkaD


