ailu:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 8.134.130.93
    port: 3307
    database: tiny_universe
    username: root
    password: 123456

    minio:
      endpoint: http://8.134.130.93:9000
      accessKey: ailu
      secretKey: 12345678
      bucket: public

  redis:
    database: 1
    host: 8.134.130.93
    port: 6379
    password: 123456

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: 8.134.130.93/xxl-job-admin
    executor:
      address: ''
      appname: tiny-universe
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999


