server:
  port: 8082

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  datasource:
    druid:
      driver-class-name: ${ailu.datasource.driver-class-name}
      url: jdbc:mysql://${ailu.datasource.host}:${ailu.datasource.port}/${ailu.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${ailu.datasource.username}
      password: ${ailu.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ailu.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      ailu:
        mapper: debug
        service: info
        controller: info
